# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    # Default:
    #   - (macOS) Menlo
    #   - (Linux) monospace
    #   - (Windows) Consolas
    #family: "Ricty Diminished"
    family: "MesloLGS NF"
    style: Regular
  bold:
    family: "MesloLGS NF"
    style: Bold
  italic:
    family: "MesloLGS NF"
    style: Italic
  size: 13

# Background Transparency
#background_opacity: 1
#background_opacity: 0.95
background_opacity: 0.8
